import _ from 'lodash';

export default contragentDaData => ({
  name_short: _.get(contragentDaData, ['value'], ''),
  name_full_with_opf: _.get(contragentDaData, ['data', 'name', 'full_with_opf'], ''),
  name_short_with_opf: _.get(contragentDaData, ['data', 'name', 'short_with_opf'], ''),
  inn: _.get(contragentDaData, ['data', 'inn'], ''),
  kpp: _.get(contragentDaData, ['data', 'kpp'], ''),
  ogrn: _.get(contragentDaData, ['data', 'ogrn'], ''),
  ogrn_date: new Date((_.get(contragentDaData, ['data', 'ogrn_date'], ''))).toLocaleString(),
  status: _.get(contragentDaData, ['data', 'state', 'status'], ''),
  okpo: _.get(contragentDaData, ['data', 'okpo'], ''),
  okato: _.get(contragentDaData, ['data', 'okato'], ''),
  oktmo: _.get(contragentDaData, ['data', 'oktmo'], ''),
  okogu: _.get(contragentDaData, ['data', 'okogu'], ''),
  okfs: _.get(contragentDaData, ['data', 'okfs'], ''),
  okved: _.get(contragentDaData, ['data', 'okved'], ''),
  opf_code: _.get(contragentDaData, ['data', 'opf', 'code'], ''),
  opf_name: _.get(contragentDaData, ['data', 'opf', 'short'], ''),
  opf_name_full: _.get(contragentDaData, ['data', 'opf', 'full'], ''),
  kladr: _.get(contragentDaData, ['data', 'address', 'data', 'kladr_id'], ''),
  fias_id: _.get(contragentDaData, ['data', 'address', 'data', 'fias_id'], ''),
  fias_code: _.get(contragentDaData, ['data', 'address', 'data', 'fias_code'], ''),
  phone: _.get(contragentDaData, ['data', 'phones'], ''),
  index: _.get(contragentDaData, ['data', 'address', 'data', 'postal_code'], ''),
  address: _.get(contragentDaData, ['data', 'address', 'unrestricted_value'], ''),
  branch_type: _.get(contragentDaData, ['data', 'branch_type'], ''),
  type: _.get(contragentDaData, ['data', 'type'], ''),
  actuality_date: new Date((_.get(contragentDaData, ['data', 'state', 'actuality_date'], ''))).toLocaleString(),
  registration_date: new Date((_.get(contragentDaData, ['data', 'state', 'registration_date'], ''))).toLocaleString(),
  liquidation_date: new Date((_.get(contragentDaData, ['data', 'state', 'liquidation_date'], ''))).toLocaleString(),
});
